const pets = [
  {
    name: "Fluffy",
    gender: "Female",
    id: 0,
    age: 2,
    color: "White",
    favFood: "Tuna",
    breed: "Abyssinian",
    url: "https://cdn2.thecatapi.com/images/0XYvRd7oD.jpg",
  },
  {
    name: "Garfield",
    gender: "Male",
    id: 1,
    age: 5,
    color: "Golden",
    favFood: "Lasagna",
    breed: "Persian",
    url: "https://cdn2.thecatapi.com/images/3Pem6K30P.jpg",
  },
  {
    name: "Mew",
    gender: "Female",
    id: 2,
    age: 6,
    color: "Black",
    favFood: "Fish",
    breed: "American Shorthair",
    url: "https://cdn2.thecatapi.com/images/JFPROfGtQ.jpg",
  },
  {
    name: "Daisy",
    gender: "Male",
    id: 3,
    age: 14,
    color: "Tabby",
    favFood: "Popcorn",
    breed: "British Shorthair",
    url: "https://cdn2.thecatapi.com/images/s4wQfYoEk.jpg",
  },
  {
    name: "Wednesday",
    gender: "Female",
    id: 4,
    age: 10,
    color: "White",
    favFood: "Ham",
    breed: "Donskoy",
    url: "https://cdn2.thecatapi.com/images/3KG57GfMW.jpg",
  },
  {
    name: "Leo",
    gender: "Male",
    id: 5,
    age: 13,
    color: "Grey",
    favFood: "Salmon",
    breed: "Malayan",
    url: "https://upload.wikimedia.org/wikipedia/commons/a/a1/BrownVarientAsianCat.JPG",
  },
  {
    name: "Gigi",
    gender: "Female",
    id: 6,
    age: 1,
    color: "Grey",
    favFood: "Yoghurt",
    breed: "Exotic Shorthair",
    url: "https://cdn2.thecatapi.com/images/YnPrYEmfe.jpg",
  },
  {
    name: "Theodore",
    gender: "Male",
    id: 7,
    age: 14,
    color: "Seal point",
    favFood: "Turkey",
    breed: "Siamese",
    url: "https://cdn2.thecatapi.com/images/ai6Jps4sx.jpg",
  },
  {
    name: "Bruno",
    gender: "Male",
    id: 8,
    age: 10,
    color: "Orange",
    favFood: "Cheese",
    breed: "Maine Coon",
    url: "https://cdn2.thecatapi.com/images/OOD3VXAQn.jpg",
  },
  {
    name: "Honey",
    gender: "Female",
    id: 9,
    age: 6,
    color: "Tortoiseshell",
    favFood: "Bananas",
    breed: "Ragamuffin",
    url: "https://cdn2.thecatapi.com/images/SMuZx-bFM.jpg",
  },
  {
    name: "Benedict",
    gender: "Male",
    id: 10,
    age: 7,
    color: "Tabby",
    favFood: "Broccoli",
    breed: "Sphinx",
    url: "https://cdn2.thecatapi.com/images/BDb8ZXb1v.jpg",
  },
  {
    name: "Luna",
    gender: "Female",
    id: 11,
    age: 4,
    color: "Golden Brown",
    favFood: "Ice Cream",
    breed: "Dragon Li",
    url: "https://cdn2.thecatapi.com/images/BQMSld0A0.jpg",
  },
  {
    name: "Nebula",
    gender: "Female",
    id: 12,
    age: 11,
    color: "Grey",
    favFood: "Carrots",
    breed: "Scottish Fold",
    url: "https://cdn2.thecatapi.com/images/o9t0LDcsa.jpg",
  },
  {
    name: "Darcy",
    gender: "Female",
    id: 13,
    age: 5,
    color: "Orange",
    favFood: "Chicken",
    breed: "LaPerm",
    url: "https://cdn2.thecatapi.com/images/aKbsEYjSl.jpg",
  },
  {
    name: "Ash",
    gender: "Male",
    id: 14,
    age: 8,
    color: "Brown",
    favFood: "Mackerel",
    breed: "Bengal",
    url: "https://cdn2.thecatapi.com/images/O3btzLlsO.png",
  },
  {
    name: "Dixie",
    gender: "Female",
    id: 15,
    age: 3,
    color: "Light Tan",
    favFood: "Melon",
    breed: "Pixebob",
    url: "https://cdn2.thecatapi.com/images/z7fJRNeN6.jpg",
  },
  {
    name: "Jude",
    gender: "Male",
    id: 16,
    age: 9,
    color: "White",
    favFood: "Spinach",
    breed: "Ragdoll",
    url: "https://cdn2.thecatapi.com/images/oGefY4YoG.jpg",
  },
  {
    name: "Dolly",
    gender: "Female",
    id: 17,
    age: 3,
    color: "White",
    favFood: "Lamb",
    breed: "Himalayan",
    url: "https://cdn2.thecatapi.com/images/CDhOtM-Ig.jpg",
  },
  {
    name: "Magic",
    gender: "Male",
    id: 18,
    age: 12,
    color: "White",
    favFood: "Eggs",
    breed: "Munchkin",
    url: "https://cdn2.thecatapi.com/images/j5cVSqLer.jpg",
  },
  {
    name: "Callie",
    gender: "Female",
    id: 19,
    age: 2,
    color: "Calico",
    favFood: "Oatmeal",
    breed: "Manx",
    url: "https://cdn2.thecatapi.com/images/fhYh2PDcC.jpg",
  },
];

module.exports = pets;
