const pets = [
  {
    name: "Fluffy",
    gender: "Female",
    id: 0,
    age: 2,
    color: "Brown",
    favFood: "Tuna",
    breed: "Abyssinian",
    url: "https://cdn2.thecatapi.com/images/0XYvRd7oD.jpg",
  },
  {
    name: "Garfield",
    gender: "Male",
    id: 1,
    age: 5,
    color: "Golden",
    favFood: "Lasagna",
    breed: "Persian",
    url: "https://cdn2.thecatapi.com/images/3Pem6K30P.jpg",
  },
  {
    name: "Mew",
    gender: "Female",
    id: 2,
    age: 6,
    color: "Tortoiseshell Smoke",
    favFood: "Fish",
    breed: "American Shorthair",
    url: "https://cdn2.thecatapi.com/images/JFPROfGtQ.jpg",
  },
  {
    name: "Henry",
    gender: "Male",
    id: 3,
    age: 14,
    color: "Grey",
    favFood: "Popcorn",
    breed: "British Shorthair",
    url: "https://cdn2.thecatapi.com/images/s4wQfYoEk.jpg",
  },
  {
    name: "Wednesday",
    gender: "Female",
    id: 4,
    age: 10,
    color: "Brown",
    favFood: "Ham",
    breed: "Donskoy",
    url: "https://cdn2.thecatapi.com/images/3KG57GfMW.jpg",
  },
  {
    name: "Leo",
    gender: "Male",
    id: 5,
    age: 13,
    color: "Grey",
    favFood: "Salmon",
    breed: "Malayan",
    url: "https://upload.wikimedia.org/wikipedia/commons/a/a1/BrownVarientAsianCat.JPG",
  },
  {
    name: "Gigi",
    gender: "Female",
    id: 6,
    age: 1,
    color: "Grey",
    favFood: "Yoghurt",
    breed: "Exotic Shorthair",
    url: "https://cdn2.thecatapi.com/images/YnPrYEmfe.jpg",
  },
  {
    name: "Theodore",
    gender: "Male",
    id: 7,
    age: 14,
    color: "Lilac point",
    favFood: "Turkey",
    breed: "Siamese",
    url: "https://upload.wikimedia.org/wikipedia/commons/2/25/Siam_lilacpoint.jpg",
  },
  {
    name: "Bruno",
    gender: "Male",
    id: 8,
    age: 10,
    color: "Orange",
    favFood: "Cheese",
    breed: "Maine Coon",
    url: "https://cdn2.thecatapi.com/images/OOD3VXAQn.jpg",
  },
  {
    name: "Honey",
    gender: "Female",
    id: 9,
    age: 6,
    color: "Cream",
    favFood: "Bananas",
    breed: "Ragamuffin",
    url: "https://upload.wikimedia.org/wikipedia/commons/f/f3/20050922AmarilloRes.jpg",
  },
  {
    name: "Benedict",
    gender: "Male",
    id: 10,
    age: 7,
    color: "Tabby",
    favFood: "Broccoli",
    breed: "Sphynx",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Sphinx2_July_2006.jpg/1200px-Sphinx2_July_2006.jpg",
  },
  {
    name: "Luna",
    gender: "Female",
    id: 11,
    age: 4,
    color: "Golden Brown",
    favFood: "Ice Cream",
    breed: "Dragon Li",
    url: "https://cdn2.thecatapi.com/images/BQMSld0A0.jpg",
  },
  {
    name: "Nebula",
    gender: "Female",
    id: 12,
    age: 11,
    color: "Grey",
    favFood: "Carrots",
    breed: "Scottish Fold",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Adult_Scottish_Fold.jpg/1200px-Adult_Scottish_Fold.jpg",
  },
  {
    name: "Darcy",
    gender: "Female",
    id: 13,
    age: 5,
    color: "Orange",
    favFood: "Chicken",
    breed: "LaPerm",
    url: "https://azure.wgp-cdn.co.uk/app-yourcat/posts/laperm.jpg?&width=480&height=480&bgcolor=ffffff&mode=crop&format=webp&webp.quality=40&scale=both",
  },
  {
    name: "Ash",
    gender: "Male",
    id: 14,
    age: 8,
    color: "Brown",
    favFood: "Mackerel",
    breed: "Bengal",
    url: "https://www.zooplus.co.uk/magazine/wp-content/uploads/2018/02/fotolia_82719975-768x582.jpg",
  },
  {
    name: "Dixie",
    gender: "Female",
    id: 15,
    age: 3,
    color: "Light Tan",
    favFood: "Melon",
    breed: "Pixebob",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/P-b_facial_features.jpg/1200px-P-b_facial_features.jpg",
  },
  {
    name: "Jude",
    gender: "Male",
    id: 16,
    age: 9,
    color: "White",
    favFood: "Spinach",
    breed: "Ragdoll",
    url: "https://cdn2.thecatapi.com/images/oGefY4YoG.jpg",
  },
  {
    name: "Dolly",
    gender: "Female",
    id: 17,
    age: 3,
    color: "Lilac-point",
    favFood: "Lamb",
    breed: "Himalayan",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Himalayan_Male_Cat_5_years_Old_Lilac_Point.jpg/1200px-Himalayan_Male_Cat_5_years_Old_Lilac_Point.jpg",
  },
  {
    name: "Magic",
    gender: "Male",
    id: 18,
    age: 12,
    color: "White",
    favFood: "Eggs",
    breed: "Munchkin",
    url: "https://cdn2.thecatapi.com/images/j5cVSqLer.jpg",
  },
  {
    name: "Callie",
    gender: "Female",
    id: 19,
    age: 2,
    color: "Calico",
    favFood: "Oatmeal",
    breed: "Manx",
    url: "https://pixfeeds.com/images/3/187007/1200-614310836-manx-calico-cat-lying-down.jpg",
  },
];

module.exports = pets;
